spring:
  profiles:
    active: dev
  application:
    name: chat-app
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:postgresql://localhost:5432/chat_db
    username: chat
    password: 563d4bfa01d5ef75ad
  jackson:
    serialization:
      write-dates-as-timestamps:  false
      fail-on-empty-beans: false
security:
  basic:
    enable: false
  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 1209600
    secret: chatapp
